# Generated by Django 5.2.4 on 2025-07-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='artists',
            new_name='interests',
        ),
        migrations.AddField(
            model_name='user',
            name='distance',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='interestedIn',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='lifestyle',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='lookingFor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='personality',
            field=models.JSONField(default=list),
        ),
    ]
