# Generated by Django 5.2.4 on 2025-08-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_swipe_user_gender_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
