# Generated by Django 5.2.4 on 2025-08-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user1_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='user2_seen',
            field=models.BooleanField(default=False),
        ),
    ]
