# Generated by Django 5.2.4 on 2025-08-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(max_length=100)),
                ('user2', models.CharField(max_length=100)),
                ('messages', models.JSONField(default=list)),
                ('last_message_time', models.DateTimeField(auto_now=True)),
                ('user1_last_read', models.DateTimeField(blank=True, null=True)),
                ('user2_last_read', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_message_time'],
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
